# this symbol used to color any text in plugin
color_symbol: "&"
# this string used to add prefix plugin in messages
msg_prefix: "&3[FH] "
# this string used to notify player when he tries to use command wrong
msg_wrong-args: "&cWrong command args!"
# this string used to notify player when he tries to use command wrong
msg_wrong-subcommand: "&cWrong subcommand for hologram!"
# this string used to notify player when he spawns hologram. %s - to paste id in
msg_spawn-holo: "&aCreate new hologram with id: %s"
# this string used to notify player when he removes hologram. %s - to paste id in
msg_remove-holo: "&aRemove hologram with id: %s"
# this string used to notify player when he tries spawns hologram with exists id
msg_exists-id: "&cThat id already exists!"
# setup for items on one page in gui editor. only (9, 18, 27, 36, 45)
gui_page-count: 45